CREATE TABLE `crm_tasks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leadId` int,
	`type` enum('follow_up','call','email','meeting','document','other') NOT NULL DEFAULT 'follow_up',
	`title` varchar(255) NOT NULL,
	`description` text,
	`dueDate` timestamp NOT NULL,
	`reminderMinutes` int DEFAULT 60,
	`priority` enum('low','medium','high','urgent') NOT NULL DEFAULT 'medium',
	`status` enum('pending','in_progress','completed','cancelled') NOT NULL DEFAULT 'pending',
	`completedAt` timestamp,
	`assignedTo` int,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `crm_tasks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `lead_activities` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leadId` int NOT NULL,
	`type` enum('note','call','email','meeting','task','stage_change','property_view','document','other') NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`callDuration` int,
	`callOutcome` enum('answered','no_answer','voicemail','busy','wrong_number'),
	`emailSubject` varchar(255),
	`meetingLocation` varchar(255),
	`meetingTime` timestamp,
	`taskDueDate` timestamp,
	`taskCompleted` boolean DEFAULT false,
	`oldStage` varchar(50),
	`newStage` varchar(50),
	`propertyId` int,
	`attachmentUrl` varchar(500),
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `lead_activities_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `lead_documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leadId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`type` enum('contract','id_document','proof_of_funds','correspondence','proposal','other') NOT NULL DEFAULT 'other',
	`url` varchar(500) NOT NULL,
	`s3Key` varchar(500),
	`fileSize` int,
	`mimeType` varchar(100),
	`uploadedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `lead_documents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`contactInquiryId` int,
	`source` enum('website','referral','social_media','advertisement','cold_call','event','other') NOT NULL DEFAULT 'website',
	`stage` enum('new','contacted','qualified','proposal','negotiation','won','lost') NOT NULL DEFAULT 'new',
	`priority` enum('cold','warm','hot') NOT NULL DEFAULT 'warm',
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100),
	`email` varchar(320) NOT NULL,
	`phone` varchar(50),
	`company` varchar(255),
	`country` varchar(100),
	`city` varchar(100),
	`budgetMin` decimal(15,2),
	`budgetMax` decimal(15,2),
	`interestedPropertyTypes` text,
	`interestedCities` text,
	`interestedPropertyIds` text,
	`timeline` enum('immediate','1_3_months','3_6_months','6_12_months','over_12_months'),
	`score` int DEFAULT 50,
	`expectedValue` decimal(15,2),
	`probability` int DEFAULT 50,
	`assignedTo` int,
	`lastContactDate` timestamp,
	`nextFollowUpDate` timestamp,
	`lostReason` text,
	`wonDate` timestamp,
	`notes` text,
	`tags` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`)
);
