CREATE TABLE `contract_documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contractId` int NOT NULL,
	`documentType` enum('id_copy','proof_of_address','payment_receipt','notary_draft','notary_final','property_document','other') NOT NULL,
	`title` varchar(255) NOT NULL,
	`fileUrl` varchar(500) NOT NULL,
	`s3Key` varchar(500),
	`fileSize` int,
	`mimeType` varchar(100),
	`uploadedBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `contract_documents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `contract_status_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contractId` int NOT NULL,
	`fromStatus` varchar(50),
	`toStatus` varchar(50) NOT NULL,
	`changedBy` int,
	`reason` text,
	`ipAddress` varchar(50),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `contract_status_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `purchase_contracts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contractNumber` varchar(50) NOT NULL,
	`userId` int NOT NULL,
	`propertyId` int NOT NULL,
	`contractType` enum('pre_contract','notary_contract') NOT NULL DEFAULT 'pre_contract',
	`buyerFirstName` varchar(100) NOT NULL,
	`buyerLastName` varchar(100) NOT NULL,
	`buyerEmail` varchar(320) NOT NULL,
	`buyerPhone` varchar(50),
	`buyerAddress` text,
	`buyerIdType` enum('passport','id_card','drivers_license'),
	`buyerIdNumber` varchar(100),
	`buyerDateOfBirth` timestamp,
	`buyerNationality` varchar(100),
	`propertyTitle` varchar(255) NOT NULL,
	`propertyLocation` varchar(255) NOT NULL,
	`propertyCity` varchar(100) NOT NULL,
	`propertyArea` decimal(10,2) NOT NULL,
	`purchasePrice` decimal(15,2) NOT NULL,
	`downPaymentPercent` decimal(5,2) NOT NULL,
	`downPaymentAmount` decimal(15,2) NOT NULL,
	`remainingAmount` decimal(15,2) NOT NULL,
	`paymentPlan` enum('full','installment') NOT NULL DEFAULT 'installment',
	`installmentMonths` int,
	`monthlyInstallment` decimal(15,2),
	`interestRate` decimal(5,2) DEFAULT '0.00',
	`expectedCompletionDate` timestamp,
	`buyerSignature` text,
	`buyerSignedAt` timestamp,
	`buyerSignedIp` varchar(50),
	`sellerSignature` text,
	`sellerSignedAt` timestamp,
	`sellerSignedBy` int,
	`status` enum('draft','pending_payment','active','withdrawal','completed','cancelled','converted') NOT NULL DEFAULT 'draft',
	`withdrawalDeadline` timestamp,
	`withdrawalRequestedAt` timestamp,
	`withdrawalReason` text,
	`downPaymentPaidAt` timestamp,
	`downPaymentTransactionId` int,
	`contractPdfUrl` varchar(500),
	`contractPdfKey` varchar(500),
	`notaryContractId` int,
	`notaryDate` timestamp,
	`notaryName` varchar(255),
	`notaryNumber` varchar(100),
	`specialConditions` text,
	`notes` text,
	`adminNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `purchase_contracts_id` PRIMARY KEY(`id`),
	CONSTRAINT `purchase_contracts_contractNumber_unique` UNIQUE(`contractNumber`)
);
