CREATE TABLE `property_drafts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`status` enum('processing','draft','pending_review','approved','rejected') NOT NULL DEFAULT 'processing',
	`developerName` varchar(255),
	`sourceDocuments` text,
	`extractedData` text,
	`adjustedData` text,
	`title` varchar(255),
	`description` text,
	`longDescription` text,
	`location` varchar(255),
	`city` varchar(100),
	`latitude` decimal(10,8),
	`longitude` decimal(11,8),
	`originalPrice` decimal(15,2),
	`sellingPrice` decimal(15,2),
	`pricePerSqm` decimal(10,2),
	`area` decimal(10,2),
	`bedrooms` int,
	`bathrooms` int,
	`yearBuilt` int,
	`propertyType` enum('apartment','house','villa','commercial','land') DEFAULT 'apartment',
	`constructionStatus` enum('planning','foundation','structure','finishing','completed'),
	`completionDate` timestamp,
	`mainImage` varchar(500),
	`images` text,
	`videos` text,
	`features` text,
	`amenities` text,
	`expectedReturn` decimal(5,2),
	`rentalGuarantee` boolean DEFAULT false,
	`rentalGuaranteePercent` decimal(5,2),
	`rentalGuaranteeDuration` int,
	`installmentAvailable` boolean DEFAULT true,
	`minDownPayment` decimal(5,2),
	`maxInstallmentMonths` int,
	`installmentInterestRate` decimal(5,2),
	`additionalServices` text,
	`adminNotes` text,
	`rejectionReason` text,
	`approvedPropertyId` int,
	`createdBy` int,
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `property_drafts_id` PRIMARY KEY(`id`)
);
