CREATE TABLE `developers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`code` varchar(50),
	`description` text,
	`logoUrl` varchar(500),
	`website` varchar(255),
	`contactPerson` varchar(255),
	`contactEmail` varchar(320),
	`contactPhone` varchar(50),
	`address` text,
	`city` varchar(100),
	`country` varchar(100) DEFAULT 'Georgien',
	`defaultMarginPercent` decimal(5,2) DEFAULT '15.00',
	`fixedMarginAmount` decimal(12,2),
	`marginType` enum('percentage','fixed','both') DEFAULT 'percentage',
	`defaultDownPaymentPercent` decimal(5,2) DEFAULT '30.00',
	`allowInstallments` boolean DEFAULT true,
	`maxInstallmentMonths` int DEFAULT 36,
	`defaultInterestRate` decimal(5,2) DEFAULT '6.00',
	`minInterestRate` decimal(5,2) DEFAULT '4.00',
	`maxInterestRate` decimal(5,2) DEFAULT '12.00',
	`defaultContractLanguage` enum('de','en','ka') DEFAULT 'de',
	`specialContractClauses` text,
	`warrantyMonths` int DEFAULT 24,
	`defaultServices` json,
	`commissionRate` decimal(5,2),
	`isActive` boolean NOT NULL DEFAULT true,
	`internalNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `developers_id` PRIMARY KEY(`id`),
	CONSTRAINT `developers_code_unique` UNIQUE(`code`)
);
